[2023-07-20T20:23:02.064+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: real_estate_etl_dag.load_task manual__2023-07-20T20:22:13.730763+00:00 [queued]>
[2023-07-20T20:23:02.075+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: real_estate_etl_dag.load_task manual__2023-07-20T20:22:13.730763+00:00 [queued]>
[2023-07-20T20:23:02.075+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-07-20T20:23:02.075+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 4
[2023-07-20T20:23:02.075+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-07-20T20:23:02.087+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_task> on 2023-07-20 20:22:13.730763+00:00
[2023-07-20T20:23:02.094+0000] {standard_task_runner.py:55} INFO - Started process 615060 to run task
[2023-07-20T20:23:02.098+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'real_estate_etl_dag', 'load_task', 'manual__2023-07-20T20:22:13.730763+00:00', '--job-id', '172', '--raw', '--subdir', 'DAGS_FOLDER/real_estate_etl_dag.py', '--cfg-path', '/tmp/tmpxuc_g526']
[2023-07-20T20:23:02.100+0000] {standard_task_runner.py:83} INFO - Job 172: Subtask load_task
[2023-07-20T20:23:02.325+0000] {task_command.py:389} INFO - Running <TaskInstance: real_estate_etl_dag.load_task manual__2023-07-20T20:22:13.730763+00:00 [running]> on host ip-172-31-34-219.ap-southeast-2.compute.internal
[2023-07-20T20:23:02.539+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=real_estate_etl_dag
AIRFLOW_CTX_TASK_ID=load_task
AIRFLOW_CTX_EXECUTION_DATE=2023-07-20T20:22:13.730763+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-20T20:22:13.730763+00:00
[2023-07-20T20:23:02.540+0000] {logging_mixin.py:137} INFO - None
[2023-07-20T20:23:02.575+0000] {logging_mixin.py:137} INFO - Error connecting to the database: connection to server at "real-estate-db.czvpezojzuuw.ap-southeast-2.rds.amazonaws.com" (172.31.48.42), port 5432 failed: fe_sendauth: no password supplied
[2023-07-20T20:23:02.575+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ubuntu/airflow/dags/real_estate_etl_dag.py", line 108, in load_to_rds
    cursor = conn.cursor()
UnboundLocalError: local variable 'conn' referenced before assignment
[2023-07-20T20:23:02.626+0000] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=real_estate_etl_dag, task_id=load_task, execution_date=20230720T202213, start_date=20230720T202302, end_date=20230720T202302
[2023-07-20T20:23:02.660+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 172 for task load_task (local variable 'conn' referenced before assignment; 615060)
[2023-07-20T20:23:02.678+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-07-20T20:23:02.797+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
