[2023-07-11T13:46:50.310+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: real_estate_etl_dag.transform_task scheduled__2023-07-10T13:45:33.130624+00:00 [queued]>
[2023-07-11T13:46:50.324+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: real_estate_etl_dag.transform_task scheduled__2023-07-10T13:45:33.130624+00:00 [queued]>
[2023-07-11T13:46:50.325+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-07-11T13:46:50.325+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 4
[2023-07-11T13:46:50.325+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-07-11T13:46:50.345+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): transform_task> on 2023-07-10 13:45:33.130624+00:00
[2023-07-11T13:46:50.363+0000] {standard_task_runner.py:55} INFO - Started process 14172 to run task
[2023-07-11T13:46:50.376+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'real_estate_etl_dag', 'transform_task', 'scheduled__2023-07-10T13:45:33.130624+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/real_estate_etl_dag.py', '--cfg-path', '/tmp/tmp5phih6kj']
[2023-07-11T13:46:50.380+0000] {standard_task_runner.py:83} INFO - Job 66: Subtask transform_task
[2023-07-11T13:46:50.585+0000] {task_command.py:389} INFO - Running <TaskInstance: real_estate_etl_dag.transform_task scheduled__2023-07-10T13:45:33.130624+00:00 [running]> on host ip-172-31-34-219.ap-southeast-2.compute.internal
[2023-07-11T13:46:50.756+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=real_estate_etl_dag
AIRFLOW_CTX_TASK_ID=transform_task
AIRFLOW_CTX_EXECUTION_DATE=2023-07-10T13:45:33.130624+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-10T13:45:33.130624+00:00
[2023-07-11T13:46:50.809+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ubuntu/airflow/dags/real_estate_etl_dag.py", line 74, in clean_data
    df = df[df['price_per_week'].str.contains('\$') & df['price_per_week'].str.contains('\d')]
  File "/home/ubuntu/venv/lib/python3.10/site-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/pandas/core/indexes/range.py", line 349, in get_loc
    raise KeyError(key)
KeyError: 'price_per_week'
[2023-07-11T13:46:50.855+0000] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=real_estate_etl_dag, task_id=transform_task, execution_date=20230710T134533, start_date=20230711T134650, end_date=20230711T134650
[2023-07-11T13:46:50.882+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 66 for task transform_task ('price_per_week'; 14172)
[2023-07-11T13:46:50.909+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-07-11T13:46:50.963+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
