[2023-07-22T17:02:44.720+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: real_estate_etl_dag.transform_task manual__2023-07-22T17:02:41.500816+00:00 [queued]>
[2023-07-22T17:02:44.770+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: real_estate_etl_dag.transform_task manual__2023-07-22T17:02:41.500816+00:00 [queued]>
[2023-07-22T17:02:44.770+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-07-22T17:02:44.771+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 4
[2023-07-22T17:02:44.771+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-07-22T17:02:44.840+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): transform_task> on 2023-07-22 17:02:41.500816+00:00
[2023-07-22T17:02:44.876+0000] {standard_task_runner.py:55} INFO - Started process 2265729 to run task
[2023-07-22T17:02:44.889+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'real_estate_etl_dag', 'transform_task', 'manual__2023-07-22T17:02:41.500816+00:00', '--job-id', '197', '--raw', '--subdir', 'DAGS_FOLDER/real_estate_etl_dag.py', '--cfg-path', '/tmp/tmpmx99vqcp']
[2023-07-22T17:02:44.894+0000] {standard_task_runner.py:83} INFO - Job 197: Subtask transform_task
[2023-07-22T17:02:45.247+0000] {task_command.py:389} INFO - Running <TaskInstance: real_estate_etl_dag.transform_task manual__2023-07-22T17:02:41.500816+00:00 [running]> on host ip-172-31-34-219.ap-southeast-2.compute.internal
[2023-07-22T17:02:45.608+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=real_estate_etl_dag
AIRFLOW_CTX_TASK_ID=transform_task
AIRFLOW_CTX_EXECUTION_DATE=2023-07-22T17:02:41.500816+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-22T17:02:41.500816+00:00
[2023-07-22T17:02:45.655+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ubuntu/airflow/dags/real_estate_etl_dag.py", line 74, in clean_data
    df = df[df['price_per_week'].str.contains('\$') & df['price_per_week'].str.contains('\d')]
  File "/home/ubuntu/venv/lib/python3.10/site-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/pandas/core/indexes/range.py", line 349, in get_loc
    raise KeyError(key)
KeyError: 'price_per_week'
[2023-07-22T17:02:45.689+0000] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=real_estate_etl_dag, task_id=transform_task, execution_date=20230722T170241, start_date=20230722T170244, end_date=20230722T170245
[2023-07-22T17:02:45.705+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 197 for task transform_task ('price_per_week'; 2265729)
[2023-07-22T17:02:45.741+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-07-22T17:02:45.777+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
