[2023-07-11T15:01:49.496+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: real_estate_etl_dag.load_task manual__2023-07-11T14:45:57.353441+00:00 [queued]>
[2023-07-11T15:01:49.506+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: real_estate_etl_dag.load_task manual__2023-07-11T14:45:57.353441+00:00 [queued]>
[2023-07-11T15:01:49.506+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-07-11T15:01:49.507+0000] {taskinstance.py:1284} INFO - Starting attempt 3 of 4
[2023-07-11T15:01:49.507+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-07-11T15:01:49.518+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_task> on 2023-07-11 14:45:57.353441+00:00
[2023-07-11T15:01:49.525+0000] {standard_task_runner.py:55} INFO - Started process 49830 to run task
[2023-07-11T15:01:49.530+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'real_estate_etl_dag', 'load_task', 'manual__2023-07-11T14:45:57.353441+00:00', '--job-id', '112', '--raw', '--subdir', 'DAGS_FOLDER/real_estate_etl_dag.py', '--cfg-path', '/tmp/tmpu35ogwcu']
[2023-07-11T15:01:49.532+0000] {standard_task_runner.py:83} INFO - Job 112: Subtask load_task
[2023-07-11T15:01:49.663+0000] {task_command.py:389} INFO - Running <TaskInstance: real_estate_etl_dag.load_task manual__2023-07-11T14:45:57.353441+00:00 [running]> on host ip-172-31-34-219.ap-southeast-2.compute.internal
[2023-07-11T15:01:49.809+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=real_estate_etl_dag
AIRFLOW_CTX_TASK_ID=load_task
AIRFLOW_CTX_EXECUTION_DATE=2023-07-11T14:45:57.353441+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-11T14:45:57.353441+00:00
[2023-07-11T15:01:49.843+0000] {logging_mixin.py:137} INFO - Connection to the database successful!
[2023-07-11T15:01:49.849+0000] {logging_mixin.py:137} INFO - Table created successfully!
[2023-07-11T15:01:49.876+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ubuntu/airflow/dags/real_estate_etl_dag.py", line 130, in load_to_rds
    data = [(row['address'], row['price_per_week'], row['beds'], row['baths'], row['parking_spaces'],
  File "/home/ubuntu/airflow/dags/real_estate_etl_dag.py", line 130, in <listcomp>
    data = [(row['address'], row['price_per_week'], row['beds'], row['baths'], row['parking_spaces'],
TypeError: string indices must be integers
[2023-07-11T15:01:49.898+0000] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=real_estate_etl_dag, task_id=load_task, execution_date=20230711T144557, start_date=20230711T150149, end_date=20230711T150149
[2023-07-11T15:01:49.909+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 112 for task load_task (string indices must be integers; 49830)
[2023-07-11T15:01:49.950+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-07-11T15:01:50.025+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
